version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: macis
      POSTGRES_USER: macis
      POSTGRES_PASSWORD:  macis
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
