export enum EnvironmentEnum {
  REFRESH_SECRET_KEY = 'REFRESH_SECRET_KEY',
  ACCESS_SECRET_KEY = 'ACCESS_SECRET_KEY',
  TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID',
  TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
  TWILIO_VERIFICATION_SERVICE_SID = 'TWILIO_VERIFICATION_SERVICE_SID',
  DATABASE_URL = 'DATABASE_URL',
}
