export const ExceptionTypes = {
  USER_NOT_FOUND: 'userNotFound',
  WRONG_PASSWORD: 'wrongPassword',
  USER_ALREADY_EXIST: 'userAlreadyExist',
  UNEXPECTED_ERROR: 'unexpectedError',
  CUSTOMER_ALREADY_EXIST: 'customerAlreadyExist',
  CUSTOMER_NOT_FOUND: 'customerNotFound',
  CURATOR_NOT_FOUND: 'curatorNotFound',
  MANAGER_NOT_FOUND: 'managerNotFound',
  CALL_NOT_FOUND: 'callNotFound',
  MEETING_NOT_FOUND: 'meetingNotFound',
  CURATION_CALL_NOT_FOUND: 'curationCallNotFound',
  CURATION_MEETING_NOT_FOUND: 'curationMeetingNotFound',
  MANAGER_MONTHLY_TARGET_ALREADY_EXIST: 'managerMonthlyTargetAlreadyExist',
  USER_CANT_DELETE_HIMSELF: 'userCantDeleteHimself',
  CATEGORY_ALREADY_EXIST: 'categoryAlreadyExist',
  CATEGORY_NOT_FOUND: 'categoryNotFound',
};
